name: BDD Tests

on:
  workflow_run:
    workflows: ["Coverage"]
    types:
      - completed
  workflow_dispatch:
    inputs:
      start:
        description: 'Start BDD Tests'
        required: false
        default: 'true'
#      java_version:
#        description: 'Java version'
#        required: false
#        default: '17'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          # java-version: ${{ inputs.java_version }}
          java-version: "17"
          cache: "maven"

      - name: Set up Docker Compose
        run: sudo apt-get install docker-compose

      - name: Build and start services
        run: docker-compose up --build -d

      - name: Wait for services to be ready
        run: |
          until [ "$(curl -s -o /dev/null -w ''%{http_code}'' http://localhost:8080/api/v1/health-check)" -eq 200 ]; do
            echo "Waiting for the service to be ready..."
            sleep 5
          done

      - name: Run BDD tests
        run: mvn test -P bdd-tests

      - name: Stop and remove services
        run: docker-compose down